# Generated by Django 4.2.30 on 2026-04-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropFirmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_loss', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('risk_per_trade', models.FloatField()),
                ('max_trades_per_day', models.IntegerField()),
                ('min_rr', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.FloatField()),
                ('exit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('lot_size', models.FloatField()),
                ('direction', models.CharField(max_length=4)),
                ('pips', models.FloatField()),
                ('pnl_usd', models.FloatField()),
                ('pnl_tzs', models.FloatField()),
                ('risk_percent', models.FloatField()),
                ('followed_rules', models.BooleanField(default=True)),
                ('rule_violation', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.asset')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.strategy')),
            ],
        ),
    ]
