# Generated by Django 4.2.30 on 2026-04-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_drawdown', models.FloatField()),
                ('max_daily_loss', models.FloatField()),
                ('risk_per_trade', models.FloatField()),
                ('min_win_rate', models.FloatField()),
                ('max_trades_per_day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
