# Generated by Django 4.2.30 on 2026-04-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_propfirmprofile_trade_risk_reward_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
