# Generated by Django 4.2.30 on 2026-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_asset_user_propfirmprofile_user_strategy_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmprofile',
            name='consistency_rule',
            field=models.FloatField(default=0),
        ),
    ]
