# Generated by Django 4.2.30 on 2026-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_propfirmprofile_consistency_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmprofile',
            name='best_day_rule',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='propfirmprofile',
            name='leverage_required',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='propfirmprofile',
            name='max_trading_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propfirmprofile',
            name='profit_target_percent',
            field=models.FloatField(default=0),
        ),
    ]
