# Generated by Django 4.2.30 on 2026-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_propfirmprofile_best_day_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('forex', 'Forex'), ('gold', 'Gold'), ('crypto', 'Crypto')], default='forex', max_length=20),
        ),
    ]
